controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# -----------------------------------------------------------------------------------------
# Professeur
# -----------------------------------------------------------------------------------------

app_professeur:
    path: /professeur
    controller: App\Controller\ProfesseurController::index

app_professeur_accueil:
    path: /professeur/accueil
    controller: App\Controller\ProfesseurController::accueil

professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouterProfesseur

professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur

professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur

professeurModifier:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifierProfesseur

professeurSupprimer:
    path: /professeur/supprimer/{id}
    controller: App\Controller\ProfesseurController::supprimerProfesseur

# -----------------------------------------------------------------------------------------
# Instrument
# -----------------------------------------------------------------------------------------

app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

app_instrument_accueil:
    path: /instrument/accueil
    controller: App\Controller\InstrumentController::accueil

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument

instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument

instrumentSupprimer:
    path: /instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimerInstrument

# -----------------------------------------------------------------------------------------
# Cours
# -----------------------------------------------------------------------------------------

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_accueilcours:
    path: /cours/accueil
    controller: App\Controller\CoursController::accueil

app_ajouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter

app_consulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

app_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours

app_cours_supprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours
    
app_coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours