controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    

# -----------------------------------------------------------------------------------------
# Professeur
# -----------------------------------------------------------------------------------------


app_professeur:
    path: /professeur
    controller: App\Controller\ProfesseurController::index

app_professeur_accueil:
    path: /professeur/accueil
    controller: App\Controller\ProfesseurController::accueil

professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouterProfesseur

professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterProfesseur

professeurLister:
    path: /professeur/lister
    controller: App\Controller\ProfesseurController::listerProfesseur

professeurModifier:
    path: /professeur/modifier/{id}
    controller: App\Controller\ProfesseurController::modifierProfesseur

professeurSupprimer:
    path: /professeur/supprimer/{id}
    controller: App\Controller\ProfesseurController::supprimerProfesseur

# -----------------------------------------------------------------------------------------
# Cours
# -----------------------------------------------------------------------------------------    
# Instrument
# -----------------------------------------------------------------------------------------

app_instrument:
    path: /instrument
    controller: App\Controller\InstrumentController::index

app_instrument_accueil:
    path: /instrument/accueil
    controller: App\Controller\InstrumentController::accueil

instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument

instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument

instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument

instrumentModifier:
    path: /instrument/modifier/{id}
    controller: App\Controller\InstrumentController::modifierInstrument

instrumentSupprimer:
    path: /instrument/supprimer/{id}
    controller: App\Controller\InstrumentController::supprimerInstrument


# -----------------------------------------------------------------------------------------
# Accessoire
# -----------------------------------------------------------------------------------------

app_accessoire:
    path: /accessoire
    controller: App\Controller\AccessoireController::index

app_accessoire_accueil:
    path: /accessoire/accueil
    controller: App\Controller\AccessoireController::accueil

accessoireAjouter:
    path: /accessoire/ajouter
    controller: App\Controller\AccessoireController::ajouterAccessoire

accessoireLister:
    path: /accessoire/lister
    controller: App\Controller\AccessoireController::listerAccessoire

accessoireConsulter:
    path: /accessoire/consulter/{id}
    controller: App\Controller\AccessoireController::consulterAccessoire

accessoireModifier:
    path: /accessoire/modifier/{id}
    controller: App\Controller\AccessoireController::modifierAccessoire

accessoireSupprimer:
    path: /accessoire/supprimer/{id}
    controller: App\Controller\AccessoireController::supprimerAccessoire
    
# -----------------------------------------------------------------------------------------
# Modele
# -----------------------------------------------------------------------------------------

app_modele:
    path: /modele
    controller: App\Controller\ModeleController::index

app_modele_accueil:
    path: /modele/accueil
    controller: App\Controller\ModeleController::accueil

modeleAjouter:
    path: /modele/ajouter
    controller: App\Controller\ModeleController::ajouterModele

modeleLister:
    path: /modele/lister
    controller: App\Controller\ModeleController::listerModele

modeleModifier:
    path: /modele/modifier/{id}
    controller: App\Controller\ModeleController::modifierModele

modeleSupprimer:
    path: /modele/supprimer/{id}
    controller: App\Controller\ModeleController::supprimerModele

# -----------------------------------------------------------------------------------------
# Cours
# -----------------------------------------------------------------------------------------

app_cours:
    path: /cours
    controller: App\Controller\CoursController::index

app_accueilcours:
    path: /cours/accueil
    controller: App\Controller\CoursController::accueil

app_ajouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter

app_consulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours

app_lister:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours

app_cours_supprimer:
    path: /cours/supprimer/{id}
    controller: App\Controller\CoursController::supprimerCours
    
app_coursModifier:
    path: /cours/modifier/{id}
    controller: App\Controller\CoursController::modifierCours

# -----------------------------------------------------------------------------------------
# Eleve
# -----------------------------------------------------------------------------------------

app_eleve:
    path: /eleve
    controller: App\Controller\EleveController::index

app_eleve_accueil:
    path: /eleve/accueil
    controller: App\Controller\EleveController::accueil

eleveAjouter:
    path: /eleve/ajouter
    controller: App\Controller\EleveController::ajouterEleve

eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve

eleveLister:
    path: /eleve/lister
    controller: App\Controller\EleveController::listerEleve

eleveModifier:
    path: /eleve/modifier/{id}
    controller: App\Controller\EleveController::modifierEleve

eleveSupprimer:
    path: /eleve/supprimer/{id}
    controller: App\Controller\EleveController::supprimerEleve
 

# -----------------------------------------------------------------------------------------
# Pret
# -----------------------------------------------------------------------------------------

app_pret:
    path: /pret
    controller: App\Controller\PretController::index

app_accueilpret:
    path: /pret/accueil
    controller: App\Controller\PretController::accueil

pre_consulter:
    path: /pret/consulter/{id}
    controller: App\Controller\PretController::consulterPret

pre_lister:
    path: /pret/lister
    controller: App\Controller\PretController::listerPret

# -----------------------------------------------------------------------------------------
# Intervention
# -----------------------------------------------------------------------------------------

app_intervention:
    path: /intervention
    controller: App\Controller\InterventionController::index

app_accueilintervention:
    path: /intervention/accueil
    controller: App\Controller\InterventionController::accueil

con_consulter:
    path: /intervention/consulter/{id}
    controller: App\Controller\InterventionController::consulterIntervention

con_lister:
    path: /intervention/lister
    controller: App\Controller\InterventionController::listerIntervention

interventionModifier:
    path: /intervention/modifier/{id}
    controller: App\Controller\InterventionController::modifierIntervention

interventionSupprimer:
    path: /intervention/supprimer/{id}
    controller: App\Controller\InterventionController::supprimerIntervention

# -----------------------------------------------------------------------------------------
# Inscription
# -----------------------------------------------------------------------------------------

insc_inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::index

insc_accueilinscription:
    path: /inscription/accueil
    controller: App\Controller\InscriptionController::accueil

insc_ajouter:
    path: /inscription/ajouter
    controller: App\Controller\InscriptionController::ajouter

insc_consulter:
    path: /inscription/consulter/{id}
    controller: App\Controller\InscriptionController::consulterInscription

insc_lister:
    path: /inscription/lister
    controller: App\Controller\InscriptionController::listerInscription

insc_cours_supprimer:
    path: /inscription/supprimer/{id}
    controller: App\Controller\InscriptionController::supprimerInscription
    
insc_coursModifier:
    path: /inscription/modifier/{id}
    controller: App\Controller\InscriptionController::modifierInscription

con_Modifier:
    path: /intervention/modifier/{id}
    controller: App\Controller\InterventionController::modifierIntervention

con_Supprimer:
    path: /intervention/supprimer/{id}
    controller: App\Controller\InterventionController::supprimerIntervention


# -----------------------------------------------------------------------------------------
# Professionnel
# -----------------------------------------------------------------------------------------

app_professionnel:
    path: /professionnel
    controller: App\Controller\ProfessionnelController::index

app_accueilprofessionnel:
    path: /professionel/accueil
    controller: App\Controller\ProfessionnelController::accueil

pro_consulter:
    path: /professionnel/consulter/{id}
    controller: App\Controller\ProfessionnelController::consulterProfessionnel

pro_lister:
    path: /professionnel/lister
    controller: App\Controller\ProfessionnelController::listerProfessionnel

professionnelModifier:
    path: /professionnel/modifier/{id}
    controller: App\Controller\ProfessionnelController::modifierProfessionnel

professionnelSupprimer:
    path: /professionnel/supprimer/{id}
    controller: App\Controller\ProfessionnelController::supprimerProfessionnel

pro_ajouter:
    path: /professionnel/ajouter
    controller: App\Controller\ProfessionnelController::ajouter